version: '3'
services: 
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    restart: always
    volumes:
      - "/opt/lns_mios/app_pmm/authmios/app:/usr/share/nginx/html:ro"
      - "/opt/lns_mios/app_pmm/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - nodered0
      - nodered1
      - phpfpm
    networks:
      - proxynet
    ports:
      - "1891:80"
      - "1892:443"

  whoami:
    image: containous/whoami
    container_name: whoami
    ports:
      - "1893:80"
    networks:
      - proxynet

  nodered0:
    container_name: nodered0
    user: root
    image: housdock/node-red-pmm:1.0
    restart: always
    user: root
    ports:
      - "1894:1880"
    volumes:
     - /opt/lns_mios/volume/client0/data:/data
    networks:
     - proxynet
     - chirpstack-docker_default

  nodered1:
    container_name: nodered1
    image: housdock/node-red-pmm:1.0
    restart: always
    user: root
    ports:
      - "1895:1880"
    volumes:
     - /opt/lns_mios/volume/client1/data:/data
     - /opt/lns_mios/volume/client1/node_modules:/usr/src/node-red/node_modules
    networks:
     - proxynet
     - chirpstack-docker_default

   nodered2:
    container_name: nodered2
    image: housdock/node-red-pmm:1.0
    restart: always
    user: root
    ports:
      - "1896:1880"
    volumes:
     - /opt/lns_mios/volume/client2/data:/data
     - /opt/lns_mios/volume/client2/node_modules:/usr/src/node-red/node_modules
    networks:
     - proxynet
     - chirpstack-docker_default

  nodered3:
    container_name: nodered3
    image: housdock/node-red-pmm:1.0
    restart: always
    user: root
    ports:
      - "1897:1880"
    volumes:
     - /opt/lns_mios/volume/client3/data:/data
     - /opt/lns_mios/volume/client3/node_modules:/usr/src/node-red/node_modules
    networks:
     - proxynet
     - chirpstack-docker_default

  nodered4:
    container_name: nodered4
    image: housdock/node-red-pmm:1.0
    restart: always
    user: root
    ports:
      - "1898:1880"
    volumes:
     - /opt/lns_mios/volume/client4/data:/data
     - /opt/lns_mios/volume/client4/node_modules:/usr/src/node-red/node_modules
    networks:
     - proxynet
     - chirpstack-docker_default    

  phpfpm:
    container_name: phpfpm
    tty: true
    image: php:fpm-alpine
    volumes:
     - "/opt/lns_mios/app_pmm/authmios/app:/script:ro" 
    networks:
     - proxynet

networks:
  proxynet:
  chirpstack-docker_default:
    external: true